#############################################################################
# Makefile for building: warehouse.app/Contents/MacOS/warehouse
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  warehouse.pro
# Template: app
# Command: /Applications/QT/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile warehouse.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/QT/5.3/clang_64/mkspecs/macx-clang -I. -I/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers -I/Applications/QT/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Applications/QT/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Applications/QT/5.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework QtSql -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Applications/QT/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		db.cpp \
		addclass.cpp moc_mainwindow.cpp \
		moc_addclass.cpp
OBJECTS       = main.o \
		mainwindow.o \
		db.o \
		addclass.o \
		moc_mainwindow.o \
		moc_addclass.o
DIST          = /Applications/QT/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.3/clang_64/mkspecs/features/spec_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/lex.prf \
		warehouse.pro main.cpp \
		mainwindow.cpp \
		db.cpp \
		addclass.cpp
QMAKE_TARGET  = warehouse
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = warehouse.app/Contents/MacOS/warehouse

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile warehouse.app/Contents/PkgInfo warehouse.app/Contents/Resources/empty.lproj warehouse.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_addclass.h $(OBJECTS)  
	@test -d warehouse.app/Contents/MacOS/ || mkdir -p warehouse.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: warehouse.pro /Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf /Applications/QT/5.3/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/qdevice.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/device_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/unix.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/macx.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang.conf \
		/Applications/QT/5.3/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/QT/5.3/clang_64/mkspecs/qconfig.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/QT/5.3/clang_64/mkspecs/features/spec_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/warn_on.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/qt.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/resources.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/moc.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/uic.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/exceptions.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/yacc.prf \
		/Applications/QT/5.3/clang_64/mkspecs/features/lex.prf \
		warehouse.pro \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/QT/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/QtSql.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile warehouse.pro
/Applications/QT/5.3/clang_64/mkspecs/features/spec_pre.prf:
/Applications/QT/5.3/clang_64/mkspecs/qdevice.pri:
/Applications/QT/5.3/clang_64/mkspecs/features/device_config.prf:
/Applications/QT/5.3/clang_64/mkspecs/common/shell-unix.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/unix.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/mac.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/macx.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/clang.conf:
/Applications/QT/5.3/clang_64/mkspecs/common/clang-mac.conf:
/Applications/QT/5.3/clang_64/mkspecs/qconfig.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/QT/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/QT/5.3/clang_64/mkspecs/features/qt_functions.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/qt_config.prf:
/Applications/QT/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/QT/5.3/clang_64/mkspecs/features/spec_post.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/default_pre.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/resolve_config.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/default_post.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/warn_on.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/qt.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/resources.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/moc.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/uic.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/unix/thread.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/mac/rez.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/exceptions.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/yacc.prf:
/Applications/QT/5.3/clang_64/mkspecs/features/lex.prf:
warehouse.pro:
/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/QT/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/QT/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Applications/QT/5.3/clang_64/lib/QtSql.framework/QtSql.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile warehouse.pro

qmake_all: FORCE

warehouse.app/Contents/PkgInfo: 
	@test -d warehouse.app/Contents || mkdir -p warehouse.app/Contents
	@$(DEL_FILE) warehouse.app/Contents/PkgInfo
	@echo "APPL????" >warehouse.app/Contents/PkgInfo
warehouse.app/Contents/Resources/empty.lproj: 
	@test -d warehouse.app/Contents/Resources || mkdir -p warehouse.app/Contents/Resources
	@touch warehouse.app/Contents/Resources/empty.lproj
	
warehouse.app/Contents/Info.plist: 
	@test -d warehouse.app/Contents || mkdir -p warehouse.app/Contents
	@$(DEL_FILE) warehouse.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.warehouse,g" -e "s,@EXECUTABLE@,warehouse,g" -e "s,@TYPEINFO@,????,g" /Applications/QT/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >warehouse.app/Contents/Info.plist
dist: 
	@test -d .tmp/warehouse1.0.0 || mkdir -p .tmp/warehouse1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/warehouse1.0.0/ && $(COPY_FILE) --parents mainwindow.h db.h addclass.h .tmp/warehouse1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp db.cpp addclass.cpp .tmp/warehouse1.0.0/ && $(COPY_FILE) --parents mainwindow.ui addclass.ui .tmp/warehouse1.0.0/ && (cd `dirname .tmp/warehouse1.0.0` && $(TAR) warehouse1.0.0.tar warehouse1.0.0 && $(COMPRESS) warehouse1.0.0.tar) && $(MOVE) `dirname .tmp/warehouse1.0.0`/warehouse1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/warehouse1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r warehouse.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_addclass.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_addclass.cpp
moc_mainwindow.cpp: /Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		db.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSql \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		mainwindow.h
	/Applications/QT/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/QT/5.3/clang_64/mkspecs/macx-clang -I/Volumes/HDD/User/code/warehouse -I/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.3/clang_64/lib/QtSql.framework/Headers -I/Applications/QT/5.3/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.3/clang_64/lib/QtCore.framework/Headers -F/Applications/QT/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_addclass.cpp: /Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		db.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSql \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		addclass.h
	/Applications/QT/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Applications/QT/5.3/clang_64/mkspecs/macx-clang -I/Volumes/HDD/User/code/warehouse -I/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Applications/QT/5.3/clang_64/lib/QtSql.framework/Headers -I/Applications/QT/5.3/clang_64/lib/QtGui.framework/Headers -I/Applications/QT/5.3/clang_64/lib/QtCore.framework/Headers -F/Applications/QT/5.3/clang_64/lib addclass.h -o moc_addclass.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_addclass.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_addclass.h
ui_mainwindow.h: mainwindow.ui
	/Applications/QT/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_addclass.h: addclass.ui
	/Applications/QT/5.3/clang_64/bin/uic addclass.ui -o ui_addclass.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		db.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSql \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		db.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSql \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		ui_mainwindow.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHeaderView \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTableWidgetItem \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		addclass.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

db.o: db.cpp db.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSql \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db.o db.cpp

addclass.o: addclass.cpp addclass.h \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		/Applications/QT/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		db.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSql \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsql.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlDatabase \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqldatabase.h \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		/Applications/QT/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlQuery \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlquery.h \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/QSqlError \
		/Applications/QT/5.3/clang_64/lib/QtSql.framework/Versions/5/Headers/qsqlerror.h \
		ui_addclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addclass.o addclass.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_addclass.o: moc_addclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addclass.o moc_addclass.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

